# Source - https://stackoverflow.com/a
# Posted by David Schmalzer
# Retrieved 2025-11-14, License - CC BY-SA 4.0

FROM influxdb:latest

COPY ./create_buckets.sh /docker-entrypoint-initdb.d
RUN chmod +x /docker-entrypoint-initdb.d/create_buckets.sh

RUN apt-get update -y && apt-get install procps -y
